//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAReportsAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n  <meta http-equiv=\"Content-Type\" co" +
            "ntent=\"text/html; charset=utf-8\" />\r\n  <meta name=\"viewport\" content=\"width=devi" +
            "ce-width, initial-scale=1\">\r\n  <title>Consolidated Security Applicance Report</t" +
            "itle>\r\n\r\n  <script type=\"text/javascript\">\r\n    // Polyfill for IE - https://dev" +
            "eloper.mozilla.org/en-US/docs/Web/API/Element/closest\r\n    if (!Element.prototyp" +
            "e.matches)\r\n      Element.prototype.matches = Element.prototype.msMatchesSelecto" +
            "r ||\r\n        Element.prototype.webkitMatchesSelector;\r\n\r\n    if (!Element.proto" +
            "type.closest)\r\n      Element.prototype.closest = function (s) {\r\n        var el " +
            "= this;\r\n        if (!document.documentElement.contains(el)) return null;\r\n     " +
            "   do {\r\n          if (el.matches(s)) return el;\r\n          el = el.parentElemen" +
            "t || el.parentNode;\r\n        } while (el !== null);\r\n        return null;\r\n     " +
            " };\r\n\r\n    function extend(obj, src) {\r\n      // Merge 2 objects into one\r\n     " +
            " Object.keys(src).forEach(function (key) { obj[key] = src[key]; });\r\n      retur" +
            "n obj;\r\n    }\r\n\r\n    function buildPath(params) {\r\n      // Takes JS object and " +
            "builds URL query params\r\n      // for the LogLine Viewer, so the user can\r\n     " +
            " // browse the data behind this report.\r\n      // modified from http://stackover" +
            "flow.com/questions/6566456/how-to-serialize-a-object-into-a-list-of-parameters\r\n" +
            "      var pairs = [];\r\n      for (var prop in params) {\r\n        if (!params.has" +
            "OwnProperty(prop)) {\r\n          continue;\r\n        }\r\n        if (Object.prototy" +
            "pe.toString.call(params[prop]) == \'[object Object]\') {\r\n          pairs.push(bui" +
            "ldPath(params[prop]));\r\n          continue;\r\n        }\r\n        pairs.push(prop " +
            "+ \'=\' + encodeURIComponent(params[prop]));\r\n      }\r\n      return pairs.join(\'&\'" +
            ");\r\n    }\r\n\r\n    function LogLineViewerURL() {\r\n      // Data attributes are ass" +
            "igned at two places:\r\n      // 1. to the context of the object calling this LogL" +
            "ineViewerURL function\r\n      // 2. to the closest parent DIV tag\r\n\r\n      // Thi" +
            "s function will be dynamically added to elements where\r\n      // loading the bac" +
            "kground data in the console is desirable\r\n\r\n      var object_params = this.datas" +
            "et;\r\n      var parent_params = this.closest(\'div\').dataset;\r\n      var params = " +
            "extend(object_params, parent_params);\r\n      var url = params.url;\r\n      delete" +
            " params[\'url\'];\r\n\r\n      var urlpath = buildPath(params);\r\n      window.open(url" +
            " + urlpath, \'_blank\');\r\n    }\r\n\r\n    document.addEventListener(\"DOMContentLoaded" +
            "\", function () {\r\n\r\n      // Set the \"onclick\" method after loading, so we have\r" +
            "\n      // access to the a tag\'s \"this\" context.\r\n      var genre_sections = docu" +
            "ment.getElementsByClassName(\'genre_sections\');\r\n      Object.keys(genre_sections" +
            ").forEach(function (key) {\r\n        genre_sections[key].onclick = LogLineViewerU" +
            "RL;\r\n      });\r\n    });\r\n\r\n\r\n    /*! pygal.js           2015-10-30 */\r\n    funct" +
            "ion init()\r\n    {\r\n    (function () { var a, b, c, d, e, f, g, h, i, j, k; i = \"" +
            "http://www.w3.org/2000/svg\", k = \"http://www.w3.org/1999/xlink\", a = function (a" +
            ", b) { return null == b && (b = null), b = b || document, Array.prototype.slice." +
            "call(b.querySelectorAll(a), 0).filter(function (a) { return a !== b }) }, e = fu" +
            "nction (a, b) { return (a.matches || a.matchesSelector || a.msMatchesSelector ||" +
            " a.mozMatchesSelector || a.webkitMatchesSelector || a.oMatchesSelector).call(a, " +
            "b) }, h = function (a, b) { return null == b && (b = null), Array.prototype.filt" +
            "er.call(a.parentElement.children, function (c) { return c !== a && (!b || e(c, b" +
            ")) }) }, Array.prototype.one = function () { return this.length > 0 && this[0] |" +
            "| {} }, f = 5, j = null, g = /translate\\((\\d+)[ ,]+(\\d+)\\)/, b = function (a) { " +
            "return (g.exec(a.getAttribute(\"transform\")) || []).slice(1).map(function (a) { r" +
            "eturn +a }) }, c = function (c) { var d, g, l, m, n, o, p, q, r, s, t, u, v, w, " +
            "x, y, z, A, B, C, D, E, F, G, H; for (a(\"svg\", c).length ? (o = a(\"svg\", c).one(" +
            "), q = o.parentElement, g = o.viewBox.baseVal, d = q.getBBox(), w = function (a)" +
            " { return (a - g.x) / g.width * d.width }, x = function (a) { return (a - g.y) /" +
            " g.height * d.height }) : w = x = function (a) { return a }, null != (null != (E" +
            " = window.pygal) ? E.config : void 0) ? null != window.pygal.config.no_prefix ? " +
            "l = window.pygal.config : (u = c.id.replace(\"chart-\", \"\"), l = window.pygal.conf" +
            "ig[u]) : l = window.config, s = null, n = a(\".graph\").one(), t = a(\".tooltip\", c" +
            ").one(), F = a(\".reactive\", c), y = 0, B = F.length; B > y; y++)m = F[y], m.addE" +
            "ventListener(\"mouseenter\", function (a) { return function () { return a.classLis" +
            "t.add(\"active\") } }(m)), m.addEventListener(\"mouseleave\", function (a) { return " +
            "function () { return a.classList.remove(\"active\") } }(m)); for (G = a(\".activate" +
            "-serie\", c), z = 0, C = G.length; C > z; z++)m = G[z], p = m.id.replace(\"activat" +
            "e-serie-\", \"\"), m.addEventListener(\"mouseenter\", function (b) { return function " +
            "() { var d, e, f, g, h, i, j, k; for (i = a(\".serie-\" + b + \" .reactive\", c), e " +
            "= 0, g = i.length; g > e; e++)d = i[e], d.classList.add(\"active\"); for (j = a(\"." +
            "serie-\" + b + \" .showable\", c), k = [], f = 0, h = j.length; h > f; f++)d = j[f]" +
            ", k.push(d.classList.add(\"shown\")); return k } }(p)), m.addEventListener(\"mousel" +
            "eave\", function (b) { return function () { var d, e, f, g, h, i, j, k; for (i = " +
            "a(\".serie-\" + b + \" .reactive\", c), e = 0, g = i.length; g > e; e++)d = i[e], d." +
            "classList.remove(\"active\"); for (j = a(\".serie-\" + b + \" .showable\", c), k = []," +
            " f = 0, h = j.length; h > f; f++)d = j[f], k.push(d.classList.remove(\"shown\")); " +
            "return k } }(p)), m.addEventListener(\"click\", function (b, d) { return function " +
            "() { var e, f, g, h, i, j, k, l, m, n, o; for (g = a(\"rect\", b).one(), h = \"\" !=" +
            "= g.style.fill, g.style.fill = h ? \"\" : \"transparent\", m = a(\".serie-\" + d + \" ." +
            "reactive\", c), i = 0, k = m.length; k > i; i++)f = m[i], f.style.display = h ? \"" +
            "\" : \"none\"; for (n = a(\".text-overlay .serie-\" + d, c), o = [], j = 0, l = n.len" +
            "gth; l > j; j++)e = n[j], o.push(e.style.display = h ? \"\" : \"none\"); return o } " +
            "}(m, p)); for (H = a(\".tooltip-trigger\", c), A = 0, D = H.length; D > A; A++)m =" +
            " H[A], m.addEventListener(\"mouseenter\", function (a) { return function () { retu" +
            "rn s = r(a) } }(m)); return t.addEventListener(\"mouseenter\", function () { retur" +
            "n null != s ? s.classList.add(\"active\") : void 0 }), t.addEventListener(\"mousele" +
            "ave\", function () { return null != s ? s.classList.remove(\"active\") : void 0 })," +
            " c.addEventListener(\"mouseleave\", function () { return j && clearTimeout(j), v(0" +
            ") }), n.addEventListener(\"mousemove\", function (a) { return !j && e(a.target, \"." +
            "background\") ? v(1e3) : void 0 }), r = function (c) { var d, e, g, m, n, o, p, r" +
            ", s, u, v, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, " +
            "V, W, X, Y, Z, $, _; for (clearTimeout(j), j = null, t.style.opacity = 1, t.styl" +
            "e.display = \"\", G = a(\"g.text\", t).one(), C = a(\"rect\", t).one(), G.innerHTML = " +
            "\"\", v = h(c, \".label\").one().textContent, N = h(c, \".x_label\").one().textContent" +
            ", J = h(c, \".value\").one().textContent, O = h(c, \".xlink\").one().textContent, D " +
            "= null, q = c, I = []; q && (I.push(q), !q.classList.contains(\"series\"));)q = q." +
            "parentElement; if (q) for (X = q.classList, R = 0, S = X.length; S > R; R++)if (" +
            "g = X[R], 0 === g.indexOf(\"serie-\")) { D = +g.replace(\"serie-\", \"\"); break } for" +
            " (y = null, null !== D && (y = l.legends[D]), o = 0, u = [[v, \"label\"]], Y = J.s" +
            "plit(\"\\n\"), r = V = 0, T = Y.length; T > V; r = ++V)E = Y[r], u.push([E, \"value-" +
            "\" + r]); for (l.tooltip_fancy_mode && (u.push([O, \"xlink\"]), u.unshift([N, \"x_la" +
            "bel\"]), u.unshift([y, \"legend\"])), H = {}, W = 0, U = u.length; U > W; W++)Z = u" +
            "[W], s = Z[0], z = Z[1], s && (F = document.createElementNS(i, \"text\"), F.textCo" +
            "ntent = s, F.setAttribute(\"x\", f), F.setAttribute(\"dy\", o), F.classList.add(0 ==" +
            "= z.indexOf(\"value\") ? \"value\" : z), 0 === z.indexOf(\"value\") && l.tooltip_fancy" +
            "_mode && F.classList.add(\"color-\" + D), \"xlink\" === z ? (d = document.createElem" +
            "entNS(i, \"a\"), d.setAttributeNS(k, \"href\", s), d.textContent = void 0, d.appendC" +
            "hild(F), F.textContent = \"Link >\", G.appendChild(d)) : G.appendChild(F), o += F." +
            "getBBox().height + f / 2, e = f, void 0 !== F.style.dominantBaseline ? F.style.d" +
            "ominantBaseline = \"text-before-edge\" : e += .8 * F.getBBox().height, F.setAttrib" +
            "ute(\"y\", e), H[z] = F); return K = G.getBBox().width + 2 * f, p = G.getBBox().he" +
            "ight + 2 * f, C.setAttribute(\"width\", K), C.setAttribute(\"height\", p), H.value &" +
            "& H.value.setAttribute(\"dx\", (K - H.value.getBBox().width) / 2 - f), H.x_label &" +
            "& H.x_label.setAttribute(\"dx\", K - H.x_label.getBBox().width - 2 * f), H.xlink &" +
            "& H.xlink.setAttribute(\"dx\", K - H.xlink.getBBox().width - 2 * f), M = h(c, \".x\"" +
            ").one(), Q = h(c, \".y\").one(), L = parseInt(M.textContent), M.classList.contains" +
            "(\"centered\") ? L -= K / 2 : M.classList.contains(\"left\") ? L -= K : M.classList." +
            "contains(\"auto\") && (L = w(c.getBBox().x + c.getBBox().width / 2) - K / 2), P = " +
            "parseInt(Q.textContent), Q.classList.contains(\"centered\") ? P -= p / 2 : Q.class" +
            "List.contains(\"top\") ? P -= p : Q.classList.contains(\"auto\") && (P = x(c.getBBox" +
            "().y + c.getBBox().height / 2) - p / 2), $ = b(t.parentElement), A = $[0], B = $" +
            "[1], L + K + A > l.width && (L = l.width - K - A), P + p + B > l.height && (P = " +
            "l.height - p - B), 0 > L + A && (L = -A), 0 > P + B && (P = -B), _ = b(t), m = _" +
            "[0], n = _[1], m === L && n === P ? c : (t.setAttribute(\"transform\", \"translate(" +
            "\" + L + \" \" + P + \")\"), c) }, v = function (a) { return j = setTimeout(function " +
            "() { return t.style.display = \"none\", t.style.opacity = 0, null != s && s.classL" +
            "ist.remove(\"active\"), j = null }, a) } }, d = function () { var b, d, e, f, g; i" +
            "f (d = a(\".pygal-chart\"), d.length) { for (g = [], e = 0, f = d.length; f > e; e" +
            "++)b = d[e], g.push(c(b)); return g } }, \"loading\" !== document.readyState ? d()" +
            " : document.addEventListener(\"DOMContentLoaded\", function () { return d() }), wi" +
            "ndow.pygal = window.pygal || {}, window.pygal.init = c, window.pygal.init_svg = " +
            "d }).call(this);}\r\n  </script>\r\n\r\n  <!-- Bootswatch styles are preferred, so loa" +
            "d last, except where overrides are needed -->\r\n\r\n  <link rel=\"stylesheet\" href=\"" +
            "https:///static/css/bootswatch_theme.min.css\" media=\"all\">\r\n\r\n\r\n  <style>\r\n    b" +
            "ody {\r\n      line-height: 1.5;\r\n      font-family: \"Roberto\", \"Helvetica Neue\", " +
            "Arial, Helvetica, sans-serif;\r\n      color: #000;\r\n      background: none;\r\n    " +
            "  font-size: 10pt;\r\n      -webkit-print-color-adjust: exact;\r\n    }\r\n\r\n    .cont" +
            "ainer {\r\n      margin-right: auto;\r\n      margin-left: auto;\r\n      padding-left" +
            ": 15px;\r\n      padding-right: 15px;\r\n      background: none;\r\n      width: 970px" +
            ";\r\n    }\r\n\r\n    hr {\r\n      box-sizing: content-box;\r\n      height: 0;\r\n    }\r\n\r" +
            "\n    hr.space {\r\n      background: #fff;\r\n      color: #fff;\r\n      visibility: " +
            "hidden;\r\n    }\r\n\r\n    h1,\r\n    h2,\r\n    h3,\r\n    h4,\r\n    h5,\r\n    h6 {\r\n      p" +
            "age-break-after: avoid;\r\n    }\r\n\r\n    blockquote {\r\n      margin: 1.5em;\r\n      " +
            "padding: 1em;\r\n      font-style: italic;\r\n      font-size: .9em;\r\n    }\r\n\r\n    t" +
            "h {\r\n      background: rgb(218, 229, 244);\r\n      text-align: center;\r\n    }\r\n\r\n" +
            "    td {\r\n      vertical-align: top;\r\n    }\r\n\r\n    figure {\r\n      margin-left: " +
            "7px;\r\n      margin-top: 0px;\r\n      margin-bottom: 0px;\r\n    }\r\n\r\n    /* duplica" +
            "te some basic classes so report still renders correctly\r\neven on non-internet co" +
            "nnected computers where bootstrap isn\'t available */\r\n    .text-center {\r\n      " +
            "text-align: center;\r\n    }\r\n\r\n    .text-left {\r\n      text-align: left;\r\n    }\r\n" +
            "\r\n    /* offset bootstrap\'s 10px margin-bottom */\r\n    p {\r\n      margin-bottom:" +
            " 0px;\r\n    }\r\n\r\n    .small {\r\n      font-size: .9em;\r\n    }\r\n\r\n    .large {\r\n   " +
            "   font-size: 1.1em;\r\n    }\r\n\r\n    .quiet {\r\n      color: #999;\r\n    }\r\n\r\n    .h" +
            "ide {\r\n      display: none;\r\n    }\r\n\r\n    .align_top {\r\n      vertical-align: to" +
            "p;\r\n    }\r\n\r\n    .pagebreak {\r\n      page-break-after: always;\r\n    }\r\n\r\n    .od" +
            "d {\r\n      background: #FFF;\r\n    }\r\n\r\n    .even {\r\n      background: #dae5f4;\r\n" +
            "    }\r\n\r\n    .fullwidth {\r\n      width: 100%;\r\n    }\r\n\r\n    .unicol,\r\n    .trico" +
            "l,\r\n    .pageviewstricol,\r\n    .quadcol {\r\n      padding: 5px;\r\n      width: 100" +
            "%;\r\n      -webkit-column-rule: 1px solid lightblue;\r\n      /* Chrome, Safari, Op" +
            "era */\r\n      -moz-column-rule: 1px solid lightblue;\r\n      /* Firefox */\r\n     " +
            " column-rule: 1px solid lightblue;\r\n    }\r\n\r\n    .tricol,\r\n    .pageviewstricol " +
            "{\r\n      -webkit-column-count: 3;\r\n      /* Chrome, Safari, Opera */\r\n      -moz" +
            "-column-count: 3;\r\n      /* Firefox */\r\n      column-count: 3;\r\n    }\r\n\r\n    .qu" +
            "adcol {\r\n      -webkit-column-count: 4;\r\n      /* Chrome, Safari, Opera */\r\n    " +
            "  -moz-column-count: 4;\r\n      /* Firefox */\r\n      column-count: 4;\r\n    }\r\n\r\n " +
            "   .unicol span,\r\n    .tricol span,\r\n    .pageviewstricol span,\r\n    .quadcol sp" +
            "an {\r\n      padding-top: 2px;\r\n    }\r\n\r\n    /* don\'t let the domain name or sear" +
            "ch term overflow */\r\n    .unicol span,\r\n    .tricol span:nth-child(1),\r\n    .pag" +
            "eviewstricol span:nth-child(1),\r\n    .quadcol span:nth-child(1) {\r\n      overflo" +
            "w: hidden;\r\n      display: inline-block;\r\n    }\r\n\r\n    .unicol span:nth-child(1)" +
            " {\r\n      width: 87%\r\n    }\r\n\r\n    .tricol span:nth-child(1) {\r\n      width: 81%" +
            "\r\n    }\r\n\r\n    .pageviewstricol span:nth-child(1) {\r\n      width: 66%\r\n    }\r\n\r\n" +
            "    .quadcol span:nth-child(1) {\r\n      width: 77%\r\n    }\r\n\r\n    .unicol div,\r\n " +
            "   .tricol div,\r\n    .pageviewstricol div,\r\n    .quadcol div {\r\n      padding-to" +
            "p: 3px;\r\n      margin-bottom: 2px;\r\n      padding-left: 10px;\r\n    }\r\n\r\n    .uni" +
            "col span:nth-child(2),\r\n    .tricol span:nth-child(2),\r\n    .pageviewstricol spa" +
            "n:nth-child(2),\r\n    .pageviewstricol span:nth-child(3),\r\n    .quadcol span:nth-" +
            "child(2) {\r\n      display: inline-block;\r\n      float: right;\r\n      text-align:" +
            " center;\r\n      border-left: 1px solid white;\r\n    }\r\n\r\n    .unicol span:nth-chi" +
            "ld(2) {\r\n      width: 10%;\r\n    }\r\n\r\n    .tricol span:nth-child(2),\r\n    .pagevi" +
            "ewstricol span:nth-child(2),\r\n    .pageviewstricol span:nth-child(3) {\r\n      wi" +
            "dth: 16%;\r\n    }\r\n\r\n    .quadcol span:nth-child(2) {\r\n      width: 22%;\r\n    }\r\n" +
            "\r\n    .urllist {\r\n      width: 100%;\r\n      border-collapse: collapse;\r\n      fo" +
            "nt-size: 10pt;\r\n      padding: 1px;\r\n      /*border-bottom:#FFF 2px solid;*/\r\n  " +
            "    overflow: hidden;\r\n      white-space: nowrap;\r\n      table-layout: fixed;\r\n " +
            "   }\r\n\r\n    .headings {\r\n      background: rgba(204, 244, 206, 0.3);\r\n      bord" +
            "er: rgba(20, 142, 84, .7) 1px solid;\r\n      border-radius: 15px;\r\n    }\r\n\r\n    ." +
            "dom_c1 {\r\n      font-size: 8.5pt;\r\n      padding-left: 5px;\r\n      border: #FFF " +
            "1px solid;\r\n      overflow: hidden;\r\n      white-space: nowrap;\r\n      font-size" +
            ": 8.5pt;\r\n      padding-left: 5px;\r\n      border: #FFF 1px solid;\r\n      overflo" +
            "w: hidden;\r\n      white-space: nowrap;\r\n      width: 75%;\r\n    }\r\n\r\n    .dom_sta" +
            "ts_c1 {\r\n      font-size: 8pt;\r\n      padding-left: 2px;\r\n      border: #FFF 1px" +
            " solid;\r\n      width: 25%;\r\n    }\r\n\r\n    .genrecol {\r\n      padding: 5px;\r\n     " +
            " margin-bottom: 20px;\r\n      -webkit-column-count: 3;\r\n      /* Chrome, Safari, " +
            "Opera */\r\n      -moz-column-count: 3;\r\n      /* Firefox */\r\n      column-count: " +
            "3;\r\n      -webkit-column-rule: 1px solid lightblue;\r\n      /* Chrome, Safari, Op" +
            "era */\r\n      -moz-column-rule: 1px solid lightblue;\r\n      /* Firefox */\r\n     " +
            " column-rule: 1px solid lightblue;\r\n    }\r\n\r\n    /*\r\nApply top margin to an hr t" +
            "ag in between Genre groups\r\nbecause webkit browsers would carry margin-bottom on" +
            " \"genrecol ol\"\r\n*/\r\n    .genrecol hr {\r\n      margin-top: 10px;\r\n      margin-bo" +
            "ttom: 0px;\r\n      border-top: 0px;\r\n    }\r\n\r\n    .genrecol a {\r\n      color: bla" +
            "ck;\r\n      text-decoration: none;\r\n    }\r\n\r\n    .genrecol ol {\r\n      margin: 0p" +
            "x;\r\n      padding-left: 0px;\r\n      list-style-type: none;\r\n      -webkit-column" +
            "-break-inside: avoid;\r\n      page-break-inside: avoid;\r\n      break-inside: avoi" +
            "d;\r\n    }\r\n\r\n    .genrecol ol li {\r\n      margin-bottom: 2px;\r\n      padding-top" +
            ": 6px;\r\n      padding-bottom: 6px;\r\n      padding-left: 5%;\r\n      border-top: r" +
            "gb(80, 80, 80) 1px solid;\r\n    }\r\n\r\n    .genrecol ol>li:first-child {\r\n      pad" +
            "ding-top: 10px;\r\n      padding-bottom: 10px;\r\n      padding-left: 3%;\r\n      fon" +
            "t-weight: bold;\r\n      font-size: 12pt;\r\n      border: rgba(141, 180, 223, 1) 2p" +
            "x solid;\r\n      background: rgba(141, 180, 223, .5);\r\n    }\r\n\r\n    .genrecol spa" +
            "n {\r\n      display: block;\r\n      width: 15%;\r\n      float: right;\r\n      text-a" +
            "lign: center;\r\n    }\r\n\r\n    /* IE10+ has SVG scaling issues */\r\n    @media scree" +
            "n and (-ms-high-contrast: active),\r\n    (-ms-high-contrast: none) {\r\n      figur" +
            "e {\r\n        width: 100%;\r\n        padding-top: 48%;\r\n        position: relative" +
            ";\r\n      }\r\n\r\n      svg {\r\n        position: absolute;\r\n        top: 0;\r\n       " +
            " left: 0;\r\n      }\r\n    }\r\n\r\n    .rating_misc,\r\n    .rating_base,\r\n    .rating_s" +
            "ilt,\r\n    .rating_sand,\r\n    .rating_pebble,\r\n    .rating_stone,\r\n    .rating_ro" +
            "ck,\r\n    .rating_boulder {\r\n      text-decoration: none;\r\n    }\r\n\r\n    .color_ke" +
            "y {\r\n      font-size: 10pt;\r\n      font-weight: bold;\r\n      text-align: center;" +
            "\r\n      margin-top: 5px;\r\n      border-collapse: separate;\r\n      border-spacing" +
            ": 3px;\r\n    }\r\n\r\n    .rating_misc {\r\n      background-color: rgba(203, 223, 218," +
            " .6);\r\n    }\r\n\r\n    .rating_base {\r\n      background-color: rgba(189, 213, 146, " +
            ".6);\r\n    }\r\n\r\n    .rating_silt {\r\n      background-color: rgba(127, 206, 106, ." +
            "6);\r\n    }\r\n\r\n    .rating_sand {\r\n      background-color: rgba(228, 214, 114, .6" +
            ");\r\n    }\r\n\r\n    .rating_pebble {\r\n      background-color: rgba(255, 174, 48, .6" +
            ");\r\n    }\r\n\r\n    .rating_stone {\r\n      background-color: rgba(255, 106, 15, .6)" +
            ";\r\n    }\r\n\r\n    .rating_rock {\r\n      background-color: rgba(229, 57, 98, .6);\r\n" +
            "    }\r\n\r\n    .rating_boulder {\r\n      background-color: rgba(235, 0, 0, .6);\r\n  " +
            "  }\r\n\r\n    /* Text colors for line text in LogLine & Search viewers. */\r\n    .te" +
            "xt_ads {\r\n      color: rgb(169, 169, 169);\r\n    }\r\n\r\n    .text_misc {\r\n      col" +
            "or: rgb(99, 127, 121);\r\n    }\r\n\r\n    .text_bse,\r\n    .text_base {\r\n      color: " +
            "rgb(141, 174, 105);\r\n    }\r\n\r\n    .text_slt,\r\n    .text_silt {\r\n      color: rgb" +
            "(71, 169, 62);\r\n    }\r\n\r\n    .text_snd,\r\n    .text_sand {\r\n      color: rgb(173," +
            " 166, 74);\r\n    }\r\n\r\n    .text_pbs,\r\n    .text_pebble {\r\n      color: rgb(244, 1" +
            "67, 46);\r\n    }\r\n\r\n    .text_stn,\r\n    .text_stone {\r\n      color: rgb(203, 86, " +
            "0);\r\n    }\r\n\r\n    .text_rck,\r\n    .text_rock {\r\n      color: rgb(218, 56, 104);\r" +
            "\n    }\r\n\r\n    .text_bld,\r\n    .text_boulder {\r\n      color: rgb(255, 0, 0);\r\n   " +
            " }\r\n\r\n    .text_af_autofix {\r\n      color: rgb(71, 169, 62);\r\n    }\r\n\r\n    .text" +
            "_af_override {\r\n      color: rgb(203, 86, 0);\r\n    }\r\n\r\n    .text_af_doubtful {\r" +
            "\n      color: rgb(218, 56, 104);\r\n    }\r\n\r\n    .text_af_rocks {\r\n      color: rg" +
            "b(255, 0, 0);\r\n    }\r\n\r\n    /* colors for pygal legend boxes */\r\n    .color-misc" +
            " {\r\n      fill: rgba(203, 223, 202, 1);\r\n    }\r\n\r\n    .color-base {\r\n      fill:" +
            " rgba(189, 213, 146, 1);\r\n    }\r\n\r\n    .color-silt {\r\n      fill: rgba(127, 206," +
            " 106, 1);\r\n    }\r\n\r\n    .color-sand {\r\n      fill: rgba(228, 214, 114, 1);\r\n    " +
            "}\r\n\r\n    .color-pebble {\r\n      fill: rgba(255, 174, 48, 1);\r\n    }\r\n\r\n    .colo" +
            "r-stone {\r\n      fill: rgba(255, 106, 15, 1);\r\n    }\r\n\r\n    .color-rock {\r\n     " +
            " fill: rgba(236, 76, 144, 1);\r\n    }\r\n\r\n    .color-boulder {\r\n      fill: rgba(2" +
            "15, 0, 0, 1);\r\n    }\r\n\r\n    .color-ads {\r\n      fill: rgba(120, 120, 120, 1);\r\n " +
            "   }\r\n\r\n    .color-allow {\r\n      fill: rgba(84, 168, 28, 1);\r\n    }\r\n\r\n    .col" +
            "or-block {\r\n      fill: rgba(213, 0, 0, 1);\r\n    }\r\n\r\n    /* end of pygal legend" +
            " box colors */\r\n\r\n    .lightbox .box {\r\n      width: -webkit-min-content;\r\n     " +
            " width: -moz-min-content;\r\n      width: min-content;\r\n      min-width: 500px;\r\n " +
            "     max-width: 600px;\r\n      margin: 2% auto;\r\n      padding: 20px;\r\n      back" +
            "ground-color: #FFF;\r\n      box-shadow: 0px 1px 26px -3px #777777;\r\n      border-" +
            "radius: 10px;\r\n      max-height: 600px;\r\n    }\r\n\r\n    .lightbox .close {\r\n      " +
            "float: right;\r\n      display: block;\r\n      text-decoration: none;\r\n      font-f" +
            "amily: Gotham, \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n      font-size:" +
            " 22px;\r\n      color: #858585;\r\n    }\r\n\r\n    .lightbox {\r\n      /** Hide the ligh" +
            "tbox */\r\n      display: none;\r\n      /** Apply basic lightbox styling */\r\n      " +
            "position: fixed;\r\n      z-index: 9999;\r\n      width: 100%;\r\n      top: 0;\r\n     " +
            " left: 0;\r\n      color: #333333;\r\n    }\r\n\r\n    .lightbox:target {\r\n      /** Sho" +
            "w lightbox when it is target */\r\n      display: block;\r\n      outline: none;\r\n  " +
            "  }\r\n\r\n    #popScroll {\r\n      display: block;\r\n      padding: 10px 0 0 0px;\r\n  " +
            "    overflow-y: auto;\r\n      max-height: 430px;\r\n    }\r\n\r\n    @page {\r\n      siz" +
            "e: 8.5in 11in;\r\n      margin-left: .3in;\r\n      margin-right: .3in;\r\n\r\n      @bo" +
            "ttom-left {\r\n        content: \"Usage Report - Anna Susan Burkholder\";\r\n        f" +
            "ont-size: 10pt;\r\n      }\r\n\r\n      @right-bottom {\r\n        content: \"\";\r\n      }" +
            "\r\n\r\n      @bottom-right {\r\n        counter-increment: page;\r\n        counter-res" +
            "et: page 1;\r\n        content: \"Page \"counter(page) \" of \"counter(pages);\r\n      " +
            "}\r\n    }\r\n\r\n    @media print {\r\n\r\n      h2 {\r\n        font-size: 16pt;\r\n      }\r" +
            "\n\r\n      h3 {\r\n        font-size: 13pt;\r\n      }\r\n\r\n      hr {\r\n        margin-t" +
            "op: 7pt;\r\n        margin-bottom: 7pt;\r\n      }\r\n\r\n      a,\r\n      p,\r\n      th,\r" +
            "\n      td,\r\n      li,\r\n      span {\r\n        font-size: 8pt;\r\n      }\r\n\r\n      p" +
            " {\r\n        margin: 0;\r\n        line-height: 1.6;\r\n      }\r\n\r\n      .container {" +
            "\r\n        padding-left: 0px;\r\n        padding-right: 0px;\r\n        width: 100%;\r" +
            "\n      }\r\n\r\n      #top_bar {\r\n        display: none;\r\n      }\r\n\r\n      .drilldow" +
            "n {\r\n        display: none;\r\n      }\r\n\r\n      .genrecol ol li {\r\n        margin-" +
            "bottom: 1px;\r\n        padding-top: 3px;\r\n        padding-bottom: 3px;\r\n      }\r\n" +
            "\r\n      .tricol div,\r\n      .quadcol div,\r\n      .pageviewstricol div {\r\n       " +
            " padding-top: 1px;\r\n      }\r\n\r\n      .tricol span,\r\n      .quadcol span,\r\n      " +
            ".pageviewstricol span {\r\n        line-height: 1;\r\n      }\r\n\r\n      .genrecol ol>" +
            "li:first-child {\r\n        padding-top: 3px;\r\n        padding-bottom: 3px;\r\n     " +
            "   font-size: 9.5pt;\r\n      }\r\n\r\n      /*\r\nmargin-bottom in the ol tag carries t" +
            "o next\r\ncolumn in webkit. last-child works a bit better\r\n*/\r\n      .genrecol ol>" +
            "li:last-child {\r\n        margin-bottom: 5px;\r\n      }\r\n\r\n    }\r\n\r\n\r\n    .report_" +
            "info {\r\n      width: 100%;\r\n    }\r\n\r\n    .info_labels {\r\n      width: 15%;\r\n    " +
            "}\r\n\r\n    .info_data {\r\n      width: 10%;\r\n    }\r\n\r\n    #browserBar {\r\n      disp" +
            "lay: none;\r\n    }\r\n\r\n    /* IE10+ has SVG scaling issues */\r\n    @media screen a" +
            "nd (-ms-high-contrast: active),\r\n    (-ms-high-contrast: none) {\r\n      #browser" +
            "Bar {\r\n        display: block;\r\n      }\r\n    }\r\n  </style>\r\n\r\n  <style>\r\n    bod" +
            "y {\r\n      width: 100vw;\r\n      height: 100vh;\r\n      padding: 0px;\r\n      margi" +
            "n: 0px;\r\n      overflow: hidden;\r\n    }\r\n\r\n    .main_div {\r\n      width: 100%;\r\n" +
            "      height: 100%;\r\n      padding: 0px;\r\n      margin: 0px;\r\n      display: fle" +
            "x;\r\n    }\r\n\r\n    .left_menu_div {\r\n      background-color: gainsboro;\r\n      wid" +
            "th: 250px;\r\n      height: 100%;\r\n      margin: 0px;\r\n      padding: 0px 5px 0px " +
            "10px;\r\n      border: solid yellow 0px;\r\n    }\r\n\r\n    .report_list {\r\n      width" +
            ": 100%;\r\n      height: calc(100% - 33px);\r\n      overflow: auto;\r\n    }\r\n\r\n    ." +
            "reports_container {\r\n      width: calc(100% - 200px);\r\n      height: 100%;\r\n    " +
            "  margin: 0px;\r\n      overflow: hidden;\r\n    }\r\n\r\n    .report_page {\r\n      back" +
            "ground-color: white;\r\n      width: 100%;\r\n      height: 100%;\r\n      margin: 0px" +
            ";\r\n      overflow: auto;\r\n      overflow-x: hidden;\r\n    }\r\n\r\n    .select_button" +
            " {\r\n      width: 100%;\r\n      margin-top: 1px;\r\n\r\n    }\r\n\r\n    [selected=\"True\"]" +
            " {\r\n      color: green;\r\n      font-weight: bold;\r\n      background-color: white" +
            ";\r\n      border: dimgray solid 0.5px;\r\n      border-radius: 2px;\r\n      height: " +
            "21px;\r\n      outline: none;\r\n    }\r\n\r\n    .table1 {\r\n      font-family: arial, s" +
            "ans-serif;\r\n      border-collapse: collapse;\r\n      width: 100%;\r\n    }\r\n\r\n    t" +
            "d,\r\n    th {\r\n      border: 1px solid #dddddd;\r\n      text-align: left;\r\n      p" +
            "adding: 2px 5px;\r\n      overflow: hidden;\r\n    }\r\n\r\n    th {\r\n    position: stic" +
            "ky;\r\n      top: 0;\r\n      border-bottom: 2px solid black;\r\n    }\r\n    tr:nth-chi" +
            "ld(even) {\r\n      background-color: #dddddd;\r\n      padding: 2px;\r\n    }\r\n    tr" +
            ":hover{\r\n      background-color: #c2f6FFAA;      \r\n    }\r\n    tr:nth-child(even)" +
            ":hover {\r\n      background-color: #c2d8d6;\r\n    }\r\n\r\n    .progress {\r\n      widt" +
            "h: calc(100% - 0px);\r\n      height: 19px;\r\n      padding: 0px 2px;\r\n      backgr" +
            "ound: -webkit-linear-gradient(left, rgb(161, 201, 161) var(--progress), rgb(218," +
            " 102, 102) calc(0% - var(--progress)));\r\n      color: black;\r\n    }\r\n  </style>\r" +
            "\n\r\n<script>\r\n    function el(id) { return document.getElementById(id); }\r\n    fu" +
            "nction selectReport(btn) {\r\n      e = el(\"report_list\");\r\n      for (var i = 0; " +
            "i < e.children.length; i++) {\r\n        e.children[i].setAttribute(\'selected\', fa" +
            "lse);\r\n      }\r\n      btn.setAttribute(\'selected\', true);\r\n      el(\'report_page" +
            "\').innerHTML = el(btn.getAttribute(\'rpt_id\')).innerHTML;\r\n      html = el(\'repor" +
            "t_page\').innerHTML;\r\n      var parser = new DOMParser();\r\n      var parsedDocume" +
            "nt = parser.parseFromString(html, \'text/html\');\r\n\r\n      // set the current page" +
            "\'s <html> contents to the newly parsed <html> content\r\n      el(\'report_page\').i" +
            "nnerHTML = html;\r\n\r\n      // get a list of all <script> tags in the new page\r\n  " +
            "    var tmpScripts = el(\'report_page\').getElementsByTagName(\'script\');\r\n      if" +
            " (tmpScripts.length > 0) {\r\n          // push all of the document\'s script tags " +
            "into an array\r\n          // (to prevent dom manipulation while iterating over do" +
            "m nodes)\r\n          var scripts = [];\r\n          for (var i = 0; i < tmpScripts." +
            "length; i++) {\r\n              scripts.push(tmpScripts[i]);\r\n          }\r\n\r\n     " +
            "     // iterate over all script tags and create a duplicate tags for each\r\n     " +
            "     for (var i = 0; i < scripts.length; i++) {\r\n              var s = document." +
            "createElement(\'script\');\r\n              s.innerHTML = scripts[i].innerHTML;\r\n\r\n " +
            "             // add the new node to the page\r\n              scripts[i].parentNod" +
            "e.appendChild(s);\r\n\r\n              // remove the original (non-executing) node f" +
            "rom the page\r\n              scripts[i].parentNode.removeChild(scripts[i]);\r\n    " +
            "      }\r\n      }\r\n      init();\r\n      init1();\r\n    }\r\n\r\n    function init1(){ " +
            "      \r\n        var domainList = document.getElementById(\'domainList\');\r\n       " +
            " var xbutton = document.getElementById(\'closeBox\');\r\n        xbutton.onclick = f" +
            "unction () {\r\n            domainList.style.display=\'\';\r\n        };\r\n    \r\n      " +
            "  // Set the \"onclick\" method after loading, so we have\r\n        // access to th" +
            "e a tag\'s \"this\" context.\r\n        var genrecols = document.getElementsByClassNa" +
            "me(\'genrecol\');\r\n    \r\n        Object.keys(genrecols).forEach(function(key){\r\n  " +
            "      var alinks = genrecols[key].getElementsByTagName(\'a\');\r\n            Object" +
            ".keys(alinks).forEach(function(key){\r\n                alinks[key].onclick = show" +
            "Genres;\r\n            });\r\n        });\r\n    }\r\n\r\n    document.addEventListener(\"D" +
            "OMContentLoaded\", function(event) { \r\n      el(\'report_page\').innerHTML = el(\'re" +
            "port_summary\').innerHTML;     \r\n    });\r\n\r\n\r\n    String.prototype.capitalize = f" +
            "unction() {\r\n            return this.charAt(0).toUpperCase() + this.slice(1);\r\n " +
            "       };\r\n        \r\n        \r\n        \r\n        \r\n        function addDomainRow" +
            "(urlTable, stats, index) {\r\n            var row = urlTable.insertRow(index);\r\n  " +
            "          var dom = row.insertCell(0);\r\n            var total = row.insertCell(1" +
            ");\r\n        \r\n            dom.innerHTML = stats[0];\r\n            dom.className =" +
            " \'dom_c1\';\r\n        \r\n            total.innerHTML = stats[1];\r\n            total" +
            ".className = \'dom_stats_c1\';\r\n        \r\n            if (index % 2 === 0) {\r\n    " +
            "        // Yes, it\'s transposed, cuz header is solid BG.\r\n            var colorc" +
            "ss = \'odd\';\r\n            } else {\r\n                var colorcss = \'even\';\r\n     " +
            "       }\r\n        \r\n            dom.classList.add(colorcss);\r\n            total." +
            "classList.add(colorcss);\r\n        }\r\n        \r\n        function showGenres() {\r\n" +
            "        \r\n            var parent_element = this.closest(\'div\');\r\n            var" +
            " gsection = parent_element.dataset.gsection;\r\n            var catname = this.dat" +
            "aset.catname;\r\n            var catdesc = this.innerHTML.split(\'(\')[0].trim();\r\n " +
            "       \r\n            document.getElementById(\'genretitle\').innerHTML = catdesc.c" +
            "apitalize() + \' Domains\';\r\n            var urlTable = document.getElementById(\'u" +
            "rlrows\');\r\n            urlTable.innerHTML = \'\';\r\n        \r\n            if (gsect" +
            "ion === \'allowed\') var cat_domains = allowed;\r\n            if (gsection === \'int" +
            "ernal\') var cat_domains = internal;\r\n            if (gsection === \'blocked\') var" +
            " cat_domains = blocked;\r\n        \r\n            var domains = cat_domains[catname" +
            "][\'domains\'];\r\n            for (var index in domains) {\r\n                if (Arr" +
            "ay.isArray(domains[index])) {\r\n                  addDomainRow(urlTable, domains[" +
            "index], index);\r\n                }\r\n            }\r\n        \r\n            var dom" +
            "ainList = document.getElementById(\'domainList\');\r\n            domainList.style.d" +
            "isplay=\'inline\';\r\n        \r\n            // Add data attributes to parent DIV for" +
            " the Modal level drilldown\r\n            var popScroll = document.getElementById(" +
            "\'popScroll\');\r\n            popScroll.dataset.category = catname;\r\n            po" +
            "pScroll.dataset.action = parent_element.dataset.action;\r\n            popScroll.d" +
            "ataset.url = \"https://whitespire.compassfoundation.io\" + parent_element.dataset." +
            "drilldown_url + \"&\";\r\n        \r\n            // ADMIN URL is whitespire.compassfo" +
            "undation.io\r\n            // drilldown_url is \r\n            var modallink = docum" +
            "ent.getElementById(\'adrilldown\');\r\n            modallink.onclick = LogLineViewer" +
            "URL;\r\n        }\r\n        \r\n        // document.addEventListener(\"DOMContentLoade" +
            "d\", function() {\r\n        \r\n        //     var domainList = document.getElementB" +
            "yId(\'domainList\');\r\n        //     var xbutton = document.getElementById(\'closeB" +
            "ox\');\r\n        //     xbutton.onclick = function () {\r\n        //         domain" +
            "List.style.display=\'\';\r\n        //     };\r\n        \r\n        //     // Set the \"" +
            "onclick\" method after loading, so we have\r\n        //     // access to the a tag" +
            "\'s \"this\" context.\r\n        //     var genrecols = document.getElementsByClassNa" +
            "me(\'genrecol\');\r\n        \r\n        //     Object.keys(genrecols).forEach(functio" +
            "n(key){\r\n        //     var alinks = genrecols[key].getElementsByTagName(\'a\');\r\n" +
            "        //         Object.keys(alinks).forEach(function(key){\r\n        //       " +
            "      alinks[key].onclick = showGenres;\r\n        //         });\r\n        //     " +
            "});\r\n        \r\n        // });\r\n\r\n\r\n\r\n  </script>\r\n\r\n</head>\r\n\r\n<body>")]
        public string HeadHtml {
            get {
                return ((string)(this["HeadHtml"]));
            }
        }
    }
}
